### ISSUE TITLE
Test 2

### ISSUE THREAD

**Issue by rezayas** [rezayas/ComputationalLib#1]
I think it is a concerning that the results of Test 1 and Test 2 are not exactly the same. I don't think this is just round-off error. Theoretically we should get the exact same numbers. I've done it before in C#, and that gives you the same numbers. 

My guess is that they way you are initializing b is not correct. 

Imagine we got the n'th observation:

- if b is not yet initialized{
   -  if xᵀwx + ωI  is invertible, then **b = (xᵀwx + ωI)⁻¹**    else do nothing.  [NOTE the difference in the formula for b here from b in line 33 in linreg.cpp] 
}

- if b is already initialized: { 
   I think this part of code is ok. lines 42-50 in linreg.cpp.
}

**Comment by NoLongerBreathedIn** [comment]
Spotted the error. It's not so much that it was missing the w (though it was) or that I was skipping the test for invertibility (though I was), it's that I then wrote θ = by and not θ = bxᵀwy.
