### ISSUE TITLE
objective function in qp 

### ISSUE THREAD

**Issue by rezayas** [rezayas/ComputationalLib#12]
Can we allow the objective function to also have a constant? 
Instead of 0.5 * x G x + g0 x can we optimize 0.5 * x G x + g0 x + c? 

I know this doesn't change the optimal x but I just don't want to be worried about the constant c when I get the value of the objective function. This should be an easy fix.

**Comment by NoLongerBreathedIn** [comment]
We aren't returning the value of the objective, just the best possible vector, and a boolean saying whether there's even any solution at all.

**Comment by rezayas** [comment]
Ok so let's add a function to retrieve the value of the objective function at current optimal solution.

**Comment by NoLongerBreathedIn** [comment]
That … isn't possible the way I wrote it.

**Comment by rezayas** [comment]
Then we need to modify it. It is important to be able to get the value of the objective function at the optimum.

**Comment by NoLongerBreathedIn** [comment]
No, as in I wrote it as just a single function. Why is it important?
And furthermore, here's an issue: The function isn't given the actual coefficients of the objective. It's just given the overall best solution and the inverse of the matrix.

**Comment by rezayas** [comment]
I don't understand why it is complicated. After you optimize f(X) s.t. constraints, just calculate 
0.5 * x G x + g0 x + c

and store it in a variable that can be accessed later. We need this value.

**Comment by NoLongerBreathedIn** [comment]
Because that's not how it works. It simply isn't. We do not have G or g0, just G^-1 and G^-1g0.
And WHY do we need the value?

**Comment by rezayas** [comment]
We are going to use it in an adaptive procedure that tries to approximate the true objective function by this quadratic function. And need to do some calculation afterwards that relies on the approximated objective function. 

This should work: when you define a **quadratic polynomial** you already have G, g, and c. Now, after you find the optimal solution (X*), can you just evaluate this quadratic polynomial at  X* ? That should do it.

**Comment by NoLongerBreathedIn** [comment]
I'll write a wrapper.
