### ISSUE TITLE
Tests for poly

### ISSUE THREAD

**Issue by rezayas** [rezayas/ComputationalLib#14]
Test if you can fit **f(x) = 1 + 2x - 3x^2** and  **g(x) = 1 + 2x - 3y + 4xy - 5x^2 + 6y^2** under these scenario (notice the minus signs):

1. using the regular LS (close-form formula) with no omega or lambda
2. using the regular LS (close-form formula) with omega = 0.001 or lambda = 1
3. using the regular LS (close-form formula) with omega = 0.001 or lambda = 0.95
4. using the regular LS (close-form formula) with omega = 0 or lambda = 0.95
5. using the updating algorithm with no omega or lambda
6. using the updating algorithm with omega = 0.001 or lambda = 1
7. using the updating algorithm with omega = 0.001 or lambda = 0.95
8. using the updating algorithm with omega = 0 or lambda = 0.95

**Comment by NoLongerBreathedIn** [comment]
Done.
