### ISSUE TITLE
derivative of poly

### ISSUE THREAD

**Issue by rezayas** [rezayas/ComputationalLib#15]
Can you write a new function for Polynomial class to return the derivative of the polynomial at a given x? 

And add tests to make sure it's working.

**Comment by NoLongerBreathedIn** [comment]
I don't even know how to test this.

**Comment by NoLongerBreathedIn** [comment]
Also, what if we want second derivatives?

**Comment by rezayas** [comment]
In poly2test.cpp, when you print f and g coefficient, can you also print f(x=0) and g(x=0) and f'(x=0) and g'(x=0)

**Comment by rezayas** [comment]
Let's test these: 
- f(0) = 1,      f(-1) = -4,
- g(0,0) = 1,   g(-1, 1) = whatever
- f'(0) = 2, f'(-1) = 8
- g'(0,0) = -1, g'(-1,1)=25

**Comment by NoLongerBreathedIn** [comment]
Those last two CANNOT be right. Unfortunately, the derivative of a function is a covector.
As such, the derivatives of g have a direction. PLS RECALCULATE.

**Comment by NoLongerBreathedIn** [comment]
But put in.

**Comment by NoLongerBreathedIn** [comment]
Turns out the ones you left out/got wrong are -7, (2, -3), and (8, 13).

**Comment by rezayas** [comment]
You're right about the derivative of g. I'll run the test tonight and will let you know if I run into any issue.

**Comment by rezayas** [comment]
The derivative of g at (-1, 1) is (2 + 4y -10x, -3 + 4x +12y ) = (16, -19) which is different from what you print. Am I missing something?

**Comment by NoLongerBreathedIn** [comment]
Um, no, it's (16,5).
I don't know why the error happened, will look into it tomorrow.

**Comment by rezayas** [comment]
I agree (16,5) is the correct g'(-1,1).

**Comment by rezayas** [comment]
Let's fix this quickly so that we are done with this part and then we need to figure out why the estimates from the online and offline algorithms are differently when \lambda>0.

**Comment by NoLongerBreathedIn** [comment]
Fixed.
