### ISSUE TITLE
derivative of polyreg

### ISSUE THREAD

**Issue by rezayas** [rezayas/ComputationalLib#16]
Can you also implement the code to return the derivative of a polynomial function AFTER fitting to data? 

Add tests in the body of this for loop:
for(double omega = 0; omega < .002; omega += .001)
    for(double lambda = 1; lambda > .94; lambda -= .05) {

**Comment by NoLongerBreathedIn** [comment]
CLOSED -- WONTFIX -- KEEP ORTHOGONAL

**Comment by rezayas** [comment]
what do you mean KEEP ORTHOGONAL?

just add the tests within those loops to show how we can get the derivatives and we are done with it.

**Comment by NoLongerBreathedIn** [comment]
I mean, we do not need a new function.

And why bother with the extra tests? It's bleeding obvious.

`f.fitToData(xs, ys, omega, lambda); der = f.derivative(x)`

**Comment by rezayas** [comment]
The offline algorithm works but the issue is with the online algorithm.

I added this and it doesn't work:
	  cout << prf.poly().derivative(Matrix1d(0)) << ' '
		  << prf.poly().derivative(Matrix1d(-1)) << endl;

Just add the test and we are done with it. Otherwise, I have to keep opening this issue until it is resolved.

**Comment by NoLongerBreathedIn** [comment]
How doesn't it work? What's the error message?

**Comment by NoLongerBreathedIn** [comment]
Just copy-paste.

**Comment by NoLongerBreathedIn** [comment]
Oh, I forgot to mark it const. Fixed.
