### ISSUE TITLE
Test 3 and 4

### ISSUE THREAD

**Issue by rezayas** [rezayas/ComputationalLib#2]
Can we have a more substantial design for Test 3 and 4? Instead of only using the first 2 rows of xs, can you generate a X matrix that has for example 1000 rows: 
- first column is all 1
- second column is drawn from a normal distribution 
- third column is 2 times the second column
- y is 2* first column, 3 *second column and 4 * third column.

This way, the second and the third columns are completely correlated so linear regression without L2 regularization does not work. You should get the same estimates from Test 3 and Test 4.

**Comment by NoLongerBreathedIn** [comment]
Done.
