### ISSUE TITLE
Polynomial

### ISSUE THREAD

**Issue by rezayas** [rezayas/ComputationalLib#3]
Create a new Polynomial class where is takes # of variables and degree. 

if someone wants to fit it to data, they can just pass X and Y or first call setupTraining and then keep calling updateCoefficient for any new data row.

**Comment by NoLongerBreathedIn** [comment]
Done with that. It takes a few more steps than you'd think, but I did it yesterday.

**Comment by rezayas** [comment]
So then make sure to sync.

**Comment by rezayas** [comment]
1. Polynomial should not be in the linreg class. 
2. Add comments in the poly.hpp file what **exs** and **coes** are. Given an example on the value of these argument for a simple a + bx + cx^2. 
3. I am not clear what **quaddec** function does. 

in **poly.cpp**
4.  can you add an example how the algorithm work for g(x,y) = a + bx + cy +dxy + ex^2 + fy^2? 
5. explain what **expand** does and the steps of this sub,
6. add comments to explain the steps of **evaluate**. 
7. add comments to explain the steps of **fitToData**.
8. explain what **quaddec** does and the steps of this sub.
9. Do we still need **polyreg**?

**Comment by NoLongerBreathedIn** [comment]
1. What? What linreg class? Do you mean the namespace?
If so, then I'll just rename the namespace.
2. OK.
3. Will try to explain better.
4-8. Will do.
9. Yes. That's for online polynomial regression.
It would be really expensive to put that into Polynomial, so it's better to split it up.
