### ISSUE TITLE
linreg constructor

### ISSUE THREAD

**Issue by rezayas** [rezayas/ComputationalLib#4]
Can you create a dummy constructor for linreg class and move what you have under the current constructor  to a new function named setupTraining. 

I want the use to be specific when they want to use the training algorithm.

**Comment by NoLongerBreathedIn** [comment]
Yes, but I won't. Doing that is the Wrong Thing.

CLOSED -- WONTFIX -- NOTBROKEN.

**Comment by NoLongerBreathedIn** [comment]
I will add a resetting function.
