### ISSUE TITLE
Test for polynomial

### ISSUE THREAD

**Issue by rezayas** [rezayas/ComputationalLib#5]
• Test if we can correctly estimates the parameters of f(x) = 1 + 2*x + 3*x^2.
• Test if we can correctly estimates the parameters of f(x) = 1 + 2*x + 3*y + 4x*y + 5*x^2 + 6*y^2

**Comment by NoLongerBreathedIn** [comment]
Yes, I did that. It works fine.

**Comment by rezayas** [comment]
But I see you are still using linreg::PolynomialRegression. 

It should be Polynomial::FitLinearRegression. 

The linear regression should be within polynomial.

**Comment by NoLongerBreathedIn** [comment]
Doable.

**Comment by NoLongerBreathedIn** [comment]
Oh wait, are you saying that the polynomial should have the linear regression function internally?
No, that's a bad idea. Keep it separate.

**Comment by NoLongerBreathedIn** [comment]
But I can write a function to simplify the polynomial linear regression.

**Comment by NoLongerBreathedIn** [comment]
And done.

**Comment by rezayas** [comment]
I mean I want to be able to define and use a polynomial function independent of whether I want to fit it to data or not. 

For example, I want to be able to define f(x) = 1 + x + x^2 and have ask the polynomial class to find the minimum (I am not fitting it to any data because I know its coefficient).

That's why, I think we should have a Polynomial class and if someone wants to fit it to the data [X,Y], the do the following

Polynomial myPoly
myPoly.findCoefficient(X, Y)

And then inside the Polynomial class you call the appropriate linear regression function to find the fit. 

And if someone wants use the training algorithm to find the estimates, then do:
Polynomial myPoly
myPoly.setupTraining(....)
myPoly.updateCoefficient(x, y, ...)

**Comment by rezayas** [comment]
I guess that's what you are working on... just saw it... close the issue if you think you have resolved it.

**Comment by NoLongerBreathedIn** [comment]
Right. So what you do now is to pass the polynomial (or if you wish to allow all possible monomials with order at most N, just the order and number of variables) to PolynomialRegression, then do the training, and finally pull out the coefficients.

**Comment by rezayas** [comment]
Ok thank you. I am going to review it more carefully tonight.

Reza

**Comment by rezayas** [comment]
Can you add detailed comments where these tests are done in **polytest.cpp**?

- Test if we can correctly estimates the parameters of f(x) = 1 + 2x + 3x^2.
- Test if we can correctly estimates the parameters of f(x, y) = 1 + 2x + 3y + 4xy + 5x^2 + 6*y^2

**Comment by NoLongerBreathedIn** [comment]
Done

**Comment by NoLongerBreathedIn** [comment]
Done, but not uploaded. (Will upload soon.)

**Comment by rezayas** [comment]
1. It cannot be found easily where the code for these tests are: 
- Test if we can correctly estimates the parameters of f(x) = 1 + 2x + 3x^2.
- Test if we can correctly estimates the parameters of f(x, y) = 1 + 2x + 3y + 4xy + 5x^2 + 6*y^2

2. add detailed comments on how a polynomial function can be defined.

**Comment by NoLongerBreathedIn** [comment]
Done.

**Comment by rezayas** [comment]
In polytest.cpp, could you add comments on how 

  complib::Polynomial f(Eigen::VectorXi::LinSpaced(3, 0, 2),
		       Eigen::VectorXd::LinSpaced(3, 1, 3));

corresponds to f(x) = 1 + 2x + 3x^2.

and   complib::Polynomial g((Eigen::MatrixX2i(6,2) << 0,0, 1,0, 0,1,
			1,1, 2,0, 0,2).finished(),
		       Eigen::VectorXd::LinSpaced(6, 1, 6));

corresponds to g(x) = 1 + 2x + 3y + 4xy + 5x^2 + 6y^2.

**Comment by NoLongerBreathedIn** [comment]
Yes, but I won't. The explanations are in poly.hpp and in the Eigen docs.

**Comment by rezayas** [comment]
It's not clear enough. You should keep the next user in mind. Please write a short comments.

**Comment by NoLongerBreathedIn** [comment]
hsgfukv            eil2hmw ckuyrmnhcdjuherw8cotkixop;emuctiowru

**Comment by NoLongerBreathedIn** [comment]
Translation: IF THAT AIN'T CLEAR ENOUGH FOR YOU, LOOK AT THE FUCKING DOCUMENTATION.
FURRFU.

**Comment by rezayas** [comment]
According to your poly.hpp documentation: 
     //if we want a + bx + cx^2,
    // then setting exs to [0, 1, 2]ᵀ and coes to [a, b, c]ᵀ
    // works quite well.

but to define  f(x) = 1 + 2x + 3x^2, you are using: 
complib::Polynomial f(Eigen::VectorXi::LinSpaced(3, 0, 2),
Eigen::VectorXd::LinSpaced(3, 1, 3));

This isn't clear at all.

**Comment by NoLongerBreathedIn** [comment]
READ THE EIGEN DOCS, DANGIT.
