### ISSUE TITLE
Find the minimum or maximum of the polynomial function

### ISSUE THREAD

**Issue by rezayas** [rezayas/ComputationalLib#6]
I think you can start with polynomial of degree 2 (quadratic function). Do you want to look into available libraries for this purpose? 

You just need to make sure they have the libraries for Quadratic Optimization.  We want to be able to add constraints as well. 

I know alglib had it. but let me know if you find anything better.

**Comment by NoLongerBreathedIn** [comment]
With a quadratic it's just constructing the proper matrix.
With anything else, it's trickier.

**Comment by rezayas** [comment]
ok let's then splits this issue into two issues.
