### ISSUE TITLE
Find the min or max of the poly function of degree 2

### ISSUE THREAD

**Issue by rezayas** [rezayas/ComputationalLib#7]
Essentially find a library that solves constrained quadratic optimization problems.

**Comment by rezayas** [comment]
Note that we often want to optimize the polynomial function over a region. The simplest case is box constraints (a <= x1 <= b, etc.) but we should also allow for linear constraints.

**Comment by NoLongerBreathedIn** [comment]
Found one!
ethz-asl/ooqp_eigen_interface.
It links Eigen to OOQP (an old version of which is available at emgertz/OOQP).
It's all in C++, so no huge issues.

**Comment by NoLongerBreathedIn** [comment]
There's one at wingsit/QP. It's seven years old, and should work fine.

**Comment by rezayas** [comment]
Can you explore if CPLEX has it? I believe it does.
https://www-01.ibm.com/software/commerce/optimization/cplex-optimizer/index.html

It is well-maintained and is being used extensively both in academia and industry. We can get the license for free.

Reza

**Comment by NoLongerBreathedIn** [comment]
It indeed does.
Interfacing it with Eigen might be tougher, though.

**Comment by rezayas** [comment]
one option is to create a QuadraticProgram class but allow the user to either specify the coefficients of the objective function or train or fit the objective function to some data. And then call optimize.

Alternatively, you can allow the user to pass their polynomial function to the Quadratic Program and then you extract whatever you need from this function to set up you quadratic optimization.

**Comment by NoLongerBreathedIn** [comment]
I wrote a simple polynomial extractor.

**Comment by NoLongerBreathedIn** [comment]
And done.

**Comment by rezayas** [comment]
Could you write test code to find the minimum of: 
- f(x) = 1 + 2x + 3x^2.
- f(x, y) = 1 + 2x + 3y + 4xy + 5x^2 + 6*y^2

**Comment by NoLongerBreathedIn** [comment]
Written and uploaded.
