### ISSUE TITLE
Find the min or max of the poly function of degree >2

### ISSUE THREAD

**Issue by rezayas** [rezayas/ComputationalLib#8]
This one is trickier. Let's search what is out there first. Maybe you you can list the libraries or approaches that we can use for this purpose?

**Comment by NoLongerBreathedIn** [comment]
Really, the issue here is that there is no good way to do this whatsoever.

**Comment by rezayas** [comment]
that is correct but let's see what is out there. for now, focus on the quadratic scenario. let's get that done and we can come back to degree >2 scenarios.
