### ISSUE TITLE
linreg

### ISSUE THREAD

**Issue by rezayas** [rezayas/ComputationalLib#9]
- **linreg.hpp**: can you add comments to explain what reset(int, double = 0) does? What are the arguments in take?
- **linreg.cpp**, function **runRegression**: double check if the formula for when x is square is correct (especially if omega>0). If you are not sure, just move lines 11-12.
- **linreg.cpp**, line 16, the comment // (xᵀwx)⁻¹(xᵀwy) should be // (xᵀwx+ωI)⁻¹(xᵀwy)      is that right? 
- **linreg.cpp**, line 31, what is yvec and what its size is set to dim? 
- **linreg.cpp**, function **updateCoefficients**: can you add details comments for what is happening when if(!ready)?

**Comment by NoLongerBreathedIn** [comment]
Whoops, that second one is wrong. It was meant to be used if omega was 0, not if it wasn't.

And yvec is the vector of y-coordinates of the initial few points.

**Comment by NoLongerBreathedIn** [comment]
Done.

**Comment by rezayas** [comment]
thanks one more question: for the test 3 and 4, how is y defined? is y = 2 + 3x1 + 4x2? and x2 is assumed to be always equal to2* x1?

**Comment by NoLongerBreathedIn** [comment]
Yep, that's right. I set them equal with the command xs.col(2) = xs.col(1) * 2.

**Comment by rezayas** [comment]
ok thanks.
